---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty
notifications:
  email: true

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  - npm run lint
  - npm test

after_script:
  - greenkeeper-lockfile-upload

deploy:
  provider: surge
  project: ./dist/
  domain: mynance.surge.sh
  skip_cleanup: true
